using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CodingProject.Models
{
    public class Country
    {
        public Country(string name, string iso)
        {
            this.Name = name;
            this.ISO = iso;
        }

        public string Name { get; private set; }
        public string ISO { get; private set; }
    }

    public class CountryDatabase
    {
        public CountryDatabase()
        {
            Countries = new List<Country>
			{
				new Country("Afghanistan", "AF"),
				new Country("Albania", "AL"),
				new Country("Algeria", "DZ"),
				new Country("American Samoa", "AS"),
				new Country("Andorra", "AD"),
				new Country("Angola", "AO"),
				new Country("Anguilla", "AI"),
				new Country("Antarctica", "AQ"),
				new Country("Antigua and Barbuda", "AG"),
				new Country("Argentina", "AR"),
				new Country("Armenia", "AM"),
				new Country("Aruba", "AW"),
				new Country("Australia", "AU"),
				new Country("Austria", "AT"),
				new Country("Azerbaijan", "AZ"),
				new Country("Bahamas", "BS"),
				new Country("Bahrain", "BH"),
				new Country("Bangladesh", "BD"),
				new Country("Barbados", "BB"),
				new Country("Belarus", "BY"),
				new Country("Belgium", "BE"),
				new Country("Belize", "BZ"),
				new Country("Benin", "BJ"),
				new Country("Bermuda", "BM"),
				new Country("Bhutan", "BT"),
				new Country("Bolivia", "BO"),
				new Country("Bosnia and Herzegovina", "BA"),
				new Country("Botswana", "BW"),
				new Country("Bouvet Island", "BV"),
				new Country("Brazil", "BR"),
				new Country("British Antarctic Territory", "BQ"),
				new Country("British Indian Ocean Territory", "IO"),
				new Country("British Virgin Islands", "VG"),
				new Country("Brunei", "BN"),
				new Country("Bulgaria", "BG"),
				new Country("Burkina Faso", "BF"),
				new Country("Burundi", "BI"),
				new Country("Cambodia", "KH"),
				new Country("Cameroon", "CM"),
				new Country("Canada", "CA"),
				new Country("Canton and Enderbury Islands", "CT"),
				new Country("Cape Verde", "CV"),
				new Country("Cayman Islands", "KY"),
				new Country("Central African Republic", "CF"),
				new Country("Chad", "TD"),
				new Country("Chile", "CL"),
				new Country("China", "CN"),
				new Country("Christmas Island", "CX"),
				new Country("Cocos [Keeling] Islands", "CC"),
				new Country("Colombia", "CO"),
				new Country("Comoros", "KM"),
				new Country("Congo - Brazzaville", "CG"),
				new Country("Congo - Kinshasa", "CD"),
				new Country("Cook Islands", "CK"),
				new Country("Costa Rica", "CR"),
				new Country("Croatia", "HR"),
				new Country("Cuba", "CU"),
				new Country("Cyprus", "CY"),
				new Country("Czech Republic", "CZ"),
				new Country("Côte d’Ivoire", "CI"),
				new Country("Denmark", "DK"),
				new Country("Djibouti", "DJ"),
				new Country("Dominica", "DM"),
				new Country("Dominican Republic", "DO"),
				new Country("Dronning Maud Land", "NQ"),
				new Country("East Germany", "DD"),
				new Country("Ecuador", "EC"),
				new Country("Egypt", "EG"),
				new Country("El Salvador", "SV"),
				new Country("Equatorial Guinea", "GQ"),
				new Country("Eritrea", "ER"),
				new Country("Estonia", "EE"),
				new Country("Ethiopia", "ET"),
				new Country("Falkland Islands", "FK"),
				new Country("Faroe Islands", "FO"),
				new Country("Fiji", "FJ"),
				new Country("Finland", "FI"),
				new Country("France", "FR"),
				new Country("French Guiana", "GF"),
				new Country("French Polynesia", "PF"),
				new Country("French Southern Territories", "TF"),
				new Country("French Southern and Antarctic Territories", "FQ"),
				new Country("Gabon", "GA"),
				new Country("Gambia", "GM"),
				new Country("Georgia", "GE"),
				new Country("Germany", "DE"),
				new Country("Ghana", "GH"),
				new Country("Gibraltar", "GI"),
				new Country("Greece", "GR"),
				new Country("Greenland", "GL"),
				new Country("Grenada", "GD"),
				new Country("Guadeloupe", "GP"),
				new Country("Guam", "GU"),
				new Country("Guatemala", "GT"),
				new Country("Guernsey", "GG"),
				new Country("Guinea", "GN"),
				new Country("Guinea-Bissau", "GW"),
				new Country("Guyana", "GY"),
				new Country("Haiti", "HT"),
				new Country("Heard Island and McDonald Islands", "HM"),
				new Country("Honduras", "HN"),
				new Country("Hong Kong SAR China", "HK"),
				new Country("Hungary", "HU"),
				new Country("Iceland", "IS"),
				new Country("India", "IN"),
				new Country("Indonesia", "ID"),
				new Country("Iran", "IR"),
				new Country("Iraq", "IQ"),
				new Country("Ireland", "IE"),
				new Country("Isle of Man", "IM"),
				new Country("Israel", "IL"),
				new Country("Italy", "IT"),
				new Country("Jamaica", "JM"),
				new Country("Japan", "JP"),
				new Country("Jersey", "JE"),
				new Country("Johnston Island", "JT"),
				new Country("Jordan", "JO"),
				new Country("Kazakhstan", "KZ"),
				new Country("Kenya", "KE"),
				new Country("Kiribati", "KI"),
				new Country("Kuwait", "KW"),
				new Country("Kyrgyzstan", "KG"),
				new Country("Laos", "LA"),
				new Country("Latvia", "LV"),
				new Country("Lebanon", "LB"),
				new Country("Lesotho", "LS"),
				new Country("Liberia", "LR"),
				new Country("Libya", "LY"),
				new Country("Liechtenstein", "LI"),
				new Country("Lithuania", "LT"),
				new Country("Luxembourg", "LU"),
				new Country("Macau SAR China", "MO"),
				new Country("Macedonia", "MK"),
				new Country("Madagascar", "MG"),
				new Country("Malawi", "MW"),
				new Country("Malaysia", "MY"),
				new Country("Maldives", "MV"),
				new Country("Mali", "ML"),
				new Country("Malta", "MT"),
				new Country("Marshall Islands", "MH"),
				new Country("Martinique", "MQ"),
				new Country("Mauritania", "MR"),
				new Country("Mauritius", "MU"),
				new Country("Mayotte", "YT"),
				new Country("Metropolitan France", "FX"),
				new Country("Mexico", "MX"),
				new Country("Micronesia", "FM"),
				new Country("Midway Islands", "MI"),
				new Country("Moldova", "MD"),
				new Country("Monaco", "MC"),
				new Country("Mongolia", "MN"),
				new Country("Montenegro", "ME"),
				new Country("Montserrat", "MS"),
				new Country("Morocco", "MA"),
				new Country("Mozambique", "MZ"),
				new Country("Myanmar [Burma]", "MM"),
				new Country("Namibia", "NA"),
				new Country("Nauru", "NR"),
				new Country("Nepal", "NP"),
				new Country("Netherlands", "NL"),
				new Country("Netherlands Antilles", "AN"),
				new Country("Neutral Zone", "NT"),
				new Country("New Caledonia", "NC"),
				new Country("New Zealand", "NZ"),
				new Country("Nicaragua", "NI"),
				new Country("Niger", "NE"),
				new Country("Nigeria", "NG"),
				new Country("Niue", "NU"),
				new Country("Norfolk Island", "NF"),
				new Country("North Korea", "KP"),
				new Country("North Vietnam", "VD"),
				new Country("Northern Mariana Islands", "MP"),
				new Country("Norway", "NO"),
				new Country("Oman", "OM"),
				new Country("Pacific Islands Trust Territory", "PC"),
				new Country("Pakistan", "PK"),
				new Country("Palau", "PW"),
				new Country("Palestinian Territories", "PS"),
				new Country("Panama", "PA"),
				new Country("Panama Canal Zone", "PZ"),
				new Country("Papua New Guinea", "PG"),
				new Country("Paraguay", "PY"),
				new Country("People's Democratic Republic of Yemen", "YD"),
				new Country("Peru", "PE"),
				new Country("Philippines", "PH"),
				new Country("Pitcairn Islands", "PN"),
				new Country("Poland", "PL"),
				new Country("Portugal", "PT"),
				new Country("Puerto Rico", "PR"),
				new Country("Qatar", "QA"),
				new Country("Romania", "RO"),
				new Country("Russia", "RU"),
				new Country("Rwanda", "RW"),
				new Country("Réunion", "RE"),
				new Country("Saint Barthélemy", "BL"),
				new Country("Saint Helena", "SH"),
				new Country("Saint Kitts and Nevis", "KN"),
				new Country("Saint Lucia", "LC"),
				new Country("Saint Martin", "MF"),
				new Country("Saint Pierre and Miquelon", "PM"),
				new Country("Saint Vincent and the Grenadines", "VC"),
				new Country("Samoa", "WS"),
				new Country("San Marino", "SM"),
				new Country("Saudi Arabia", "SA"),
				new Country("Senegal", "SN"),
				new Country("Serbia", "RS"),
				new Country("Serbia and Montenegro", "CS"),
				new Country("Seychelles", "SC"),
				new Country("Sierra Leone", "SL"),
				new Country("Singapore", "SG"),
				new Country("Slovakia", "SK"),
				new Country("Slovenia", "SI"),
				new Country("Solomon Islands", "SB"),
				new Country("Somalia", "SO"),
				new Country("South Africa", "ZA"),
				new Country("South Georgia and the South Sandwich Islands", "GS"),
				new Country("South Korea", "KR"),
				new Country("Spain", "ES"),
				new Country("Sri Lanka", "LK"),
				new Country("Sudan", "SD"),
				new Country("Suriname", "SR"),
				new Country("Svalbard and Jan Mayen", "SJ"),
				new Country("Swaziland", "SZ"),
				new Country("Sweden", "SE"),
				new Country("Switzerland", "CH"),
				new Country("Syria", "SY"),
				new Country("São Tomé and Príncipe", "ST"),
				new Country("Taiwan", "TW"),
				new Country("Tajikistan", "TJ"),
				new Country("Tanzania", "TZ"),
				new Country("Thailand", "TH"),
				new Country("Timor-Leste", "TL"),
				new Country("Togo", "TG"),
				new Country("Tokelau", "TK"),
				new Country("Tonga", "TO"),
				new Country("Trinidad and Tobago", "TT"),
				new Country("Tunisia", "TN"),
				new Country("Turkey", "TR"),
				new Country("Turkmenistan", "TM"),
				new Country("Turks and Caicos Islands", "TC"),
				new Country("Tuvalu", "TV"),
				new Country("U.S. Minor Outlying Islands", "UM"),
				new Country("U.S. Miscellaneous Pacific Islands", "PU"),
				new Country("U.S. Virgin Islands", "VI"),
				new Country("Uganda", "UG"),
				new Country("Ukraine", "UA"),
				new Country("Union of Soviet Socialist Republics", "SU"),
				new Country("United Arab Emirates", "AE"),
				new Country("United Kingdom", "GB"),
				new Country("United States", "US"),
				new Country("Uruguay", "UY"),
				new Country("Uzbekistan", "UZ"),
				new Country("Vanuatu", "VU"),
				new Country("Vatican City", "VA"),
				new Country("Venezuela", "VE"),
				new Country("Vietnam", "VN"),
				new Country("Wake Island", "WK"),
				new Country("Wallis and Futuna", "WF"),
				new Country("Western Sahara", "EH"),
				new Country("Yemen", "YE"),
				new Country("Zambia", "ZM"),
				new Country("Zimbabwe", "ZW"),
			};
        }

        public List<Country> Countries
        {
            get;
            private set;
        }
    }
}